sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_install:
  - pwd
  - date -u
  - uname -a

  # Out-of-source build
  - cd ..
  - mkdir SimpleElastix-build
  - cd SimpleElastix-build

before_script:
  - export OMP_NUM_THREADS=2
  - echo $OMP_NUM_THREADS

script:
  - cmake ../SimpleElastix/SuperBuild
  - make --jobs=2 | grep -v '^--' | grep -v '^Installing'

notifications:
  slack:
    secure: h43Xu8fWhyJeuLNuvGHM5GglU5j03eDZD1obwAbe0Xccr/UyY0Cm7YA2sRtzCHKsEUaOheP6UeUuhLR9dQb0ByhDjMnEbZJViZoYzuTNaaP8Olv0GWe43CrMB2fQpOcGPfdzDNfmIrW/+kK9Yhq3Rw9UlE0O2Kk7DHebhxG2zIU=

matrix:
  allow_failures:
    - compiler: gcc # gcc sometimes hit time limit
