language: cpp

env:
  global:
    ExternalData_OBJECT_STORES=${HOME}/.ExternalData
    SIMPLEELASTIX_SOURCE_DIR=${TRAVIS_BUILD_DIR}
    SIMPLEELASTIX_BUILD_DIR=${SIMPLEELASTIX_SOURCE_DIR}/bld
    CMAKE_DOWNLOAD_FILE=cmake-3.6.0-Linux-x86_64.sh

cache:
  directories:
    - ${ExternalData_OBJECT_STORES}
    
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get remove cmake && sudo apt-get install swig lua5.1; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ${ExternalData_OBJECT_STORES} && if [[ ! -e ${CMAKE_DOWNLOAD_FILE} ]]; then curl -sSO https://cmake.org/files/v3.6/${CMAKE_DOWNLOAD_FILE}; fi; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "y\n" | sudo bash "${ExternalData_OBJECT_STORES}/${CMAKE_DOWNLOAD_FILE}" --prefix=/usr/local --exclude-subdir; fi
  - cmake --version
  - export OMP_NUM_THREADS=2
  - mkdir -p ${SIMPLEELASTIX_BUILD_DIR}

script:
  - cd ${SIMPLEELASTIX_BUILD_DIR}
  - cmake -DWRAP_LUA:BOOL=OFF -DWRAP_PYTHON:BOOL=OFF -DWRAP_JAVA:BOOL=OFF -DWRAP_CSHARP:BOOL=OFF -DWRAP_TCL:BOOL=OFF -DWRAP_R:BOOL=OFF -DWRAP_RUBY:BOOL=OFF -DBUILD_EXAMPLES:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DCMAKE_BUILD_TYPE=Release  ${SIMPLEELASTIX_SOURCE_DIR}
  - make --jobs=2
