sudo: required
dist: trusty

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

before_script:
  - export OMP_NUM_THREADS=2
  - echo $OMP_NUM_THREADS
  # Out-of-source build
  - cd ..
  - mkdir SimpleElastix-build
  - cd SimpleElastix-build

script:
  - cmake ../SimpleElastix/SuperBuild
  - make --jobs=2
